### PR TITLE
Converting Joomla content HTML to markdown

### PR DESCRIPTION
**Pull request by matt6697**
Converting HTML to markdown with https://github.com/furstenheim/copy-down, ATX style md headings

### CODE REVIEW

**Comment by matt6697** [comment]
Testing needed before beeing able to mark this as "ready for review" but PR open for collaborative brainstorm on the feature.

**Comment by matt6697** [comment]
Image links are not preserved during the conversion process : `Image ALT` gets converted into `alt="Image ALT`

The leading / of the link is missing

**Comment by matt6697** [comment]
The `'` character is converted into `\"`

**Comment by matt6697** [comment]
Markdown conversion when creating the JoomlaContent object makes both **ensureAllImageUrlsAreCorrect** and **urlSorter** functions inactive which seems to be the root cause of the image links issue. 

Markdown conversion has to be moved into the **buildTomlOutput** function. However, as we would like to preserve HTML code of custom HTML modules which will be converted using this function, a new boolean parameter should be added to the **buildTomlOutput** function to activate (or not) markdown conversion.

**Comment by davetcc** [comment]
To be honest, I converted my last site from Joomla so long ago that I've almost forgotten how this works. I've been reading through it again and I think the markdown conversion is a great idea. I still have a few older pages left that are still HTML in my sites. To be honest, they will probably not be converted in the short term. 

A question that I'm not sure of the answer to, should the html->md conversion be optional? I'm thinking i case it doesn't work properly or something.

**Comment by matt6697** [comment]
I agree ! ;-) HTML to markdown conversion is now configurable with a new **htmltomarkdown** parameter which has been set by default to **true**  to comply with Hugo guidelines. Conversion can now be disabled if needed.

Could you have a look and review this PR ?

**Review by davetcc — APPROVED** [review]

**Pull request merged**
