### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by rimas-kudelis**
I think these are small enough to be in a single PR, at least in this case. The changes proposed here are:

- using `LEFT JOIN` in `SELECT` queries instead of `WHERE`. This allows exporting articles with missing authors and/or categories
- `JoomlaContent::isPublished()` now only returns `true` if the article was marked as `Published` in Joomla. Previously it would return `true` for `Unpublished` articles as well, but not for `Archived` or `Trashed` articles, and was used to filter out which articles not to export at all. After this update, all articles will be exported, but those not currently `Published` in Joomla will be marked as `draft: true`. Perhaps the filtering logic could be reintroduced, but use some new property.
- the `created` date of Joomla articles is now exported as `date`, and `modified` date as `lastmod` (previously, only `modified` date was exported as `date`). I myself actually used the `publish_up` value as `date` field, but that should probably be exported into the `publishDate` field instead. I didn't try that scenario though, so leaving this nuance as-is.
- two seemingly unused `*.toml.ftl` templates have been removed.

I didn't even look at tests, so it's possible that some are now failing.

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
@davetcc, care to review? I'd like to delete my fork already.

**Comment by davetcc** [comment]
Apologies, I had not noticed this, I will review immediately.

**Review by davetcc — APPROVED** [review]
All good, thanks for raising the PR, and apologies for the delay in reviewing.

**Comment by rimas-kudelis** [comment]
Thank you! :)

**Pull request merged**
