### PR TITLE
Convert custom html modules to hugo shortcodes & mysql fix

### PR DESCRIPTION
**Pull request by matt6697**
- Extraction of active custom HTML modules from joomla and conversion to shortcode (raw HTML, no markdown conversion)
- Fixed deprecated mysql driverClassName after driver update

### CODE REVIEW

**Comment by davetcc** [comment]
Please can you try changing the google Guava dependency in this PR too, as we are getting a dependbot alert because it's too old at the moment? Usually, the guava library is pretty good with backward compatibility.

      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>[30.0-jre,)</version>
      </dependency>

I'll try and setup a workspace again for this project soon.

**Comment by matt6697** [comment]
Shortcodes filenames have to be changed to replace whitespaces, dots, ... with `_`
We might think to rename filenames to lowercase

**Comment by matt6697** [comment]
Sanitized converted custom HTML modules filenames with the following algorithm :

```
private String sanitizeFilename(String inputName) {
        //Replace all non a-zA-Z0-9-_ chars, convert string to lowercase, remove trailing _ after conversion
        StringBuilder sb = new StringBuilder(inputName.replaceAll("[^a-zA-Z0-9-_]", "_").toLowerCase());
        while (sb.length() > 0 && sb.charAt(sb.length() - 1) == '_') {
            sb.setLength(sb.length() - 1);
        }
        
        return sb.toString();
    }
}
```

@davetcc : Could you please review this PR ?

**Review by davetcc — APPROVED** [review]

**Comment by davetcc** [comment]
Looks great again. Many thanks!
Dave

**Pull request merged**
