### PR TITLE
Fix/utf8 encoding

### PR DESCRIPTION
**Pull request by matt6697**
- Fixed encoding warning message during build. 
- Explicit UTF-8 encoding of generated html and markdown files

### CODE REVIEW

**Comment by matt6697** [comment]
Waiting for @joshuabeny1999 validation on a windows platform

**Review by davetcc — APPROVED** [review]

**Comment by davetcc** [comment]
I've given you write access to the repo, can you try and merge this one to ensure it has worked.

**Comment by davetcc** [comment]
This should also fix issue #10

**Comment by joshuabeny1999** [comment]
> Waiting for @joshuabeny1999 validation on a windows platform

I validate that UTF-8 is fixed. Wrote in the issue something else i dedected.

**Pull request merged**
